### ISSUE TITLE
4.1.1 什么是 Source Map npm 包问题？

### ISSUE THREAD

**Issue by jjeejj** [nswbmw/node-in-debugging#11]
在 4.1.1 什么是 Source Map 章节中 用的  `uglify-es` 和 `source-map-support ` 这两个`npm`包在 [https://www.npmjs.com/](https://www.npmjs.com/) 网站 找不到的啊

**Comment by jjeejj** [comment]
直接在网站 搜索是查询不出来的，但是可以用 google或者百度 找到对应的 npm包
[uglify-es](https://www.npmjs.com/package/uglify-es)
[source-map-support](https://www.npmjs.com/package/source-map-support)

这是为什么呢？

**Comment by nswbmw** [comment]
应该是 npm 的 bug，之前应该可以搜到的。
